import { Paper } from '../types';

interface S2Paper {
  paperId: string;
  title: string;
  abstract: string | null;
  year: number | null;
  publicationDate: string | null;
  authors: { name: string }[];
  journal: { name: string } | null;
  url: string | null;
  citationCount: number;
  openAccessPdf: { url: string } | null;
  externalIds: { DOI?: string; ArXiv?: string };
}

// Helper to determine year range based on UserPreferences
const getYearFilter = (timeRange: '24h' | 'week' | 'month'): string => {
  const currentYear = new Date().getFullYear();
  // Semantic Scholar API uses 'year' ranges like '2023-'
  // Since specific date filtering is hard via API query alone, we fetch recent years and filter in memory
  return `${currentYear - 1}-`; 
};

export const searchSemanticScholar = async (query: string, timeRange: '24h' | 'week' | 'month', limit: number = 20): Promise<Paper[]> => {
  try {
    const fields = 'paperId,title,abstract,year,publicationDate,authors,journal,url,citationCount,openAccessPdf,externalIds';
    const yearFilter = getYearFilter(timeRange);
    
    // Construct URL
    const apiUrl = `https://api.semanticscholar.org/graph/v1/paper/search?query=${encodeURIComponent(query)}&fields=${fields}&limit=${limit}&year=${yearFilter}`;

    const response = await fetch(apiUrl);
    
    if (!response.ok) {
        if (response.status === 429) {
            console.warn("Semantic Scholar Rate Limit Hit. Waiting...");
            // Simple fallback: empty return, forcing UI to handle it
            return [];
        }
        throw new Error(`Semantic Scholar API Error: ${response.statusText}`);
    }

    const data = await response.json();
    
    if (!data.data || !Array.isArray(data.data)) {
        return [];
    }

    const rawPapers: S2Paper[] = data.data;

    // Post-filter by date if strict '24h' or 'week' is needed, as API is year-based
    const now = new Date();
    const msMap = {
        '24h': 24 * 60 * 60 * 1000,
        'week': 7 * 24 * 60 * 60 * 1000,
        'month': 30 * 24 * 60 * 60 * 1000,
    };
    
    const timeLimit = msMap[timeRange];

    const filteredRaw = rawPapers.filter(p => {
        if (!p.publicationDate) return true; // Keep if unknown, LLM can judge
        const pubDate = new Date(p.publicationDate);
        return (now.getTime() - pubDate.getTime()) <= timeLimit;
    });

    // Convert to App Paper format (but Title/Summary are still English here)
    // We strictly use DOI or ArXiv links if available for reliability
    return filteredRaw.map(p => {
        const primaryUrl = p.openAccessPdf?.url || (p.externalIds?.DOI ? `https://doi.org/${p.externalIds.DOI}` : p.url);
        
        return {
            id: p.paperId,
            title: p.title, // English, needs translation later
            authors: p.authors.map(a => a.name),
            summary: p.abstract || "No abstract available.", // English
            publishedDate: p.publicationDate || `${p.year}-01-01`,
            url: primaryUrl || undefined,
            journal: p.journal?.name || (p.externalIds?.ArXiv ? "arXiv" : "Unknown Journal"),
            impactFactor: p.citationCount > 0 ? `Cited by ${p.citationCount}` : undefined,
            citationCount: p.citationCount,
            openAccessPdf: p.openAccessPdf?.url,
            tags: [], // Will be filled by caller
            relevanceScore: 0, // Will be scored by LLM
            keyTakeaway: "", // Will be generated by LLM
        };
    });

  } catch (error) {
    console.error("Semantic Scholar Search Error:", error);
    return [];
  }
};